name: push to dockerhub

on:
  workflow_dispatch:

  push:
    tags:
      - 'v*'

jobs:
  update_server:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: get latest tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        id: get-latest-tag
        with:
          fallback: latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.amd64
          push: true
          tags: beclab/cloudflared:${{ steps.get-latest-tag.outputs.tag }}
                    
